
#Machine Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage (Joules).
	rotaryCondensentrator = "320000"
	#Base energy storage (Joules).
	nutritionalLiquifier = "160000"
	#Base energy storage (Joules).
	digitalMiner = "2560000"
	#Base energy storage (Joules).
	energizedSmelter = "320000"
	#Base energy storage (Joules).
	seismicVibrator = "320000"
	#Base energy storage (Joules).
	isotopicCentrifuge = "640000"
	#Base energy storage (Joules). Also defines max output rate.
	spsPort = "1000000000"
	#Base energy storage (Joules).
	teleporter = "5000000"
	#Base energy storage (Joules).
	laser = "2000000"
	#Base energy storage (Joules).
	modificationStation = "40000"
	#Base energy storage (Joules).
	chemicalInjectionChamber = "1280000"
	#Base energy storage (Joules).
	crusher = "160000"
	#Base energy storage (Joules).
	pressurizedReactionBase = "16000"
	#Base energy storage (Joules).
	chemicalInfuser = "640000"
	#Base energy storage (Joules).
	formulaicAssemblicator = "40000"
	#Base energy storage (Joules).
	osmiumCompressor = "80000"
	#Base energy storage (Joules).
	precisionSawmill = "20000"
	#Base energy storage (Joules). Also defines max process rate.
	antiprotonicNucleosynthesizer = "1000000000"
	#Base energy storage (Joules).
	combiner = "40000"
	#Base energy storage (Joules).
	metallurgicInfuser = "40000"
	#Base energy storage (Joules).
	purificationChamber = "1280000"
	#Base energy storage (Joules).
	oxidationChamber = "1280000"
	#Base energy storage (Joules).
	chemicalCrystallizer = "640000"
	#Base energy storage (Joules).
	fluidicPlenisher = "40000"
	#Base energy storage (Joules).
	chargePad = "512000"
	#Base energy storage (Joules).
	electrolyticSeparator = "160000"
	#Base energy storage (Joules).
	electricPump = "40000"
	#Base energy storage (Joules).
	enrichmentChamber = "120000"
	#Base energy storage (Joules).
	chemicalDissolutionChamber = "160000"
	#Base energy storage (Joules).
	chemicalWasher = "80000"

