
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "400"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "800"
	#Energy per operation tick (Joules).
	digitalMiner = "6400"
	#Energy per operation tick (Joules).
	energizedSmelter = "400"
	#Energy per operation tick (Joules).
	seismicVibrator = "800"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "1600"
	#Energy per operation tick (Joules).
	laser = "160000"
	#Energy per operation tick (Joules).
	modificationStation = "100"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "3200"
	#Energy per operation tick (Joules).
	crusher = "400"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "40"
	#Energy per operation tick (Joules).
	chemicalInfuser = "1600"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "100"
	#Energy per operation tick (Joules).
	osmiumCompressor = "100"
	#Energy per operation tick (Joules).
	precisionSawmill = "50"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "100000"
	#Energy per operation tick (Joules).
	combiner = "50"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "200"
	#Energy per operation tick (Joules).
	purificationChamber = "3200"
	#Energy per operation tick (Joules).
	oxidationChamber = "3200"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "1600"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "100"
	#Energy per operation tick (Joules).
	electricPump = "100"
	#Energy per operation tick (Joules).
	enrichmentChamber = "300"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "400"
	#Energy per operation tick (Joules).
	chemicalWasher = "200"

	#Teleporter
	[usage.teleporter]
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "100"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "1000000"
		#Base Joules cost for a teleportation.
		teleporterBase = "10000"

